Dockerfile
dependencies.txt

20.04 (latest) does not come with Python 3.10, so we have to install it from deadsnakes. However, 22.04 does, so we can remove deadsnakes.

Switch base-docker from 20.04 to 22.04

---

Dockerfile

Previously, we copied the contents of the project directory to the image. The contents of this directory are likely to change often, because Dependabot is configured to check dependencies every week.
A change to production dependencies should trigger a layer (and its downstream layers) to be rebuilt; indeed, it does, but earlier in the Dockerfile. A change to development dependencies should not trigger a layer (and its downstream layers) to be rebuilt, however. To prevent this, we copy only the package to the image, rather than the contents of the project directory.

Optimize build by copying only package to image

---

sqlrunner/main.py

The user and password credentials may be quoted; that is, they may contain special characters that have been escaped with `%xx`. If they are (or do), then we should unquote them.
This behaviour mirrors cohort-extractor. See
`cohortextractor.mssql_utils.mssql_connection_params_from_url`. Thanks for spotting this, @bloodearnest.

Unquote user and password credentials

---

sqlrunner/__main__.py
sqlrunner/main.py
tests/test_main.py

At present, an SQL Runner action breaks a local run (e.g. `opensafely run run_all`, because it cannot connect to a database. This makes it hard to test a pipeline that includes an SQL Runner action.
By adding the `--dummy-data-file` argument to the CLI, we make it easier to test such a pipeline. Whilst a user must create a dummy data file themselves, they can nevertheless check that any downstream actions, which would otherwise expect an output from the SQL Runner action, work as expected.
Closes #32

Add `--dummy-data-file` argument to CLI

---

.gitignore
pyproject.toml

By default (according to --help as of v22.8.0) black is already ignoring this list of directories:
/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn|_build|buck-out|build|dist|__pypackages__)/
We were using --exclude which overwrote this list.  Black supports --extend-exclude which builds upon this list and also makes use of the repos .gitignore [1].  Since we we want both git and black to ignore the files for this repo can drop all black config here.
1: https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore
Refs: opensafely-core/repo-template#85

Remove unnecessary black config

---

requirements.dev.txt

pytest added this optional dependency for installs using <3.11 back in June 2022, and included it as part of the 7.2.0 release.  It's unclear why dependabot didn't pick up this extra dependency when it bumped pytest to 7.2.0.

Re-compiled requirements to pick up exceptiongroup from pytest

---

sqlrunner/__main__.py

This allows us to commit `--dummy-data-file` to *project.yaml*, such that the associated SQL Runner action is run against dummy data when run locally and when run in CI, but run against a database when run in production.
You'll notice that whilst the functions called from *\_\_main__.py* are tested, the `if`/`else` within *\_\_main__.py* is not. This follows the advice within the Python documentation. For more information, see: https://docs.python.org/3.10/library/__main__.html?highlight=__main__%20py#id1
I briefly considered making `--dummy-data-file` and `--dsn` mutually exclusive with `ArgumentParser.add_mutually_exclusive_group`, but the point here is to commit both to *project.yaml*.
Closes #46

Ignore `--dummy-data-file` in production

---

sqlrunner/main.py
tests/test_main.py

Previously, we fetched results as a list of dicts. That's fine, when the number of results is small; less so, when the number of results is large, because eventually we run out of memory. If we stream the results, then we need not worry about running out of memory.

Stream results

---

.flake8

flake8 v6 seems to be particular about inline comments (see the note at [1]) and line continuation characters.
[1]: https://flake8.pycqa.org/en/stable/user/configuration.html

Placate flake8

---

sqlrunner/main.py
tests/test_main.py

Ideally, we'd only support compressed outputs, but that would be
a backwards incompatible change.

feat: support compressed csv outputs

---

requirements.prod.in
requirements.prod.txt
sqlrunner/__main__.py
sqlrunner/main.py
tests/conftest.py
tests/test_main.py

#86 asks for metadata. However, after discussing the issue with @ghickman, I think it should ask for logging. This is because adding logging would provide finer-grained information (3f182b0, bf6bba1) and would mean SQL Runner actions fit better into an `opensafely exec` workflow.
We want to write logs to a file (for downstream actions) and to stdout (for `opensafely exec`). Ideally, we'd format the former as JSON and the latter as text. However, doing so is [ambitious][1], so instead we take [a simpler approach][2] and format both as JSON (2feb866).
Closes #86 
[1]: https://www.structlog.org/en/stable/standard-library.html#rendering-using-structlog-based-formatters-within-logging
[2]: https://www.structlog.org/en/stable/standard-library.html#rendering-within-structlog

Add logging

---

.pre-commit-config.yaml
sqlrunner/__init__.py
sqlrunner/main.py
tests/test_main.py

The aim is to ensure a user doesn't forget about t100s.
Closes opensafely-core/t1oos#14

Add "light touch" t100 check

---

pyproject.toml
sqlrunner/__init__.py
sqlrunner/__main__.py
sqlrunner/main.py
tests/conftest.py
tests/test___main__.py
tests/test_main.py

#130 reminded me that SQL Runner has become rather gangly. In this PR, I attempt to make it less so by:
* Testing the core of the program
* Separating code into "outward-facing" (`__main__.py`) and "inward-facing" (`main.py`) modules
* Removing several low-value tests
* Raising T1OO errors in the core of the program
* Renaming T100 to T1OO[^1]
I'd suggest stepping through this PR commit-by-commit.
[^1]: I'm still annoyed at myself for making this error, and even worse, for making it inconsistently.

Make SQL Runner less gangly

---

sqlrunner/__main__.py
tests/test___main__.py

Because we often want to supply both of these arguments -- for local/CI and production use -- we can't make them mutually exclusive. However, we want to raise an error (or, at least, raise a more informative error) if they are both missing, because it's impossible for SQL Runner to do anything useful.

Error if dsn and dummy-data-file are both missing

---

.github/workflows/build_and_publish.yml
justfile

This commit first modifies the docker-build recipe to build the sqlrunner-dev image by default (and modifies the tag, build, and publish workflow to ensure that the sqlrunner image is still built on successful merge to main). It then adds a docker-build-for-os-cli recipe to tag the sqlrunner-dev image, such that sqlrunner:dev is picked up by the OpenSAFELY CLI (opensafely run, opensafely exec).
Why? So that we can make changes to a local SQL Runner, and test them against a local study. Doing so is useful when you want to debug odd SQL Runner behaviour in your local study.

Add docker-build-for-os-cli recipe

---

sqlrunner/__main__.py
sqlrunner/main.py
sqlrunner/utils.py

Although `FileHandler` touches the log file, it doesn't create any parent directories. If a user passes a path to the log file that includes non-existent parent directories, then SQL Runner will error with a `FileNotFoundError`. If SQL Runner touches the log file, making any parent directories as required, then it won't error.

Touch the log file

---

requirements.prod.in
requirements.prod.txt
sqlrunner/main.py
tests/test_main.py

Fixes #93
This implementation elects to use the T-SQL dialect-specific parser (as spoken by mssql and thus TPP backend). The generic one fails on mssqlisms like square brackets around identifiers. This might not be compatible with other backends that speak other dialects.
`sqlglot`'s optimi~s~zer provides a `qualify_columns()` function that will (amongst other things) expand out `*`s into full column names which is what is needed to write out the dummy file header.
As implemented, there's no mutual exclusion between "running" the sql query and generating the column headers. This may or may not be the ideal. I considered making generate headers a subcommand which would then no longer require the output file arg, however I couldn't find an elegant way of not making this a breaking change to …

Generate column headers

---

sqlrunner/main.py
tests/test_main.py

Fixes #98 
This required a few interconnected changes to make stdout behave like a file in all the ways we need it to so unfortunately is presented as a bit of a monster monolithic commit.

Write to stdout if no output file arg provided

---

sqlrunner/__main__.py
tests/test___main__.py
tests/test_main.py

SQL Runner should write column headers when `dsn` and `dummy-data-file` are both None (#93). The check in `__main__.py` prevents that, so we remove the check and update the associated test (67a7a21).
To get to this commit, we add more comprehensive end-to-end tests (3e0d6c3). Why?
SQL Runner has three command-line arguments that determine its behaviour: `dsn`, `dummy-data-file`, and `output`. Each can take a string or None. In 3e0d6c3, we set `output` to a string (a path). Consequently, SQL Runner's behaviour is as follows:
| dsn  | dummy-data-file | Behaviour                         |
|------|-----------------|-----------------------------------|
| dsn  | path            | Query DB, write results to output |
| dsn  | None            | Query DB, write results to output |
| None | path …

Fix writing column headers

---

sqlrunner/__main__.py
sqlrunner/main.py
tests/test___main__.py
tests/test_main.py

This refactors the `write_results` function, and returns it to its signature prior to #160. We want to output to stdout, if an output file isn't supplied. Whilst `sys.stdout` behaves like a file-like object, we don't want to close it, as we would an output file. Rather than accomplish this through type checking and try/finally, we instead use a different context manager to output to `sys.stdout`. Hopefully, doing so makes the `write_results` function easier to reason about.
(This is the approach we take to outputting to stdout in ehrQL. See [the `write_dataset_csv` function][1].)
[1]: https://github.com/opensafely-core/ehrql/blob/e863a3409c6c0473109dbfe3d1567c50eacb9b30/ehrql/file_formats/csv.py#L10-L18

Refactor `write_results`

---

tests/databases.py
tests/support/mssql/entrypoint.sh

Copying the commit message from the equivalent PR on ehrql: https://github.com/opensafely-core/ehrql/pull/2120
The previous version was incompatible with the updated kernel now used by Github Actions runners. See:
microsoft/mssql-docker#868
The fix has been backported as far as the 2019 image, but not to the 2017 image. Seeing that the 2017 image didn't match what was being run in production in any case we might as well upgrade.
This requires a few small changes:
* The `sqlcmd` tool has moved from `/opt/mssql-tools/bin` to `/opt/mssql-tools18/bin`. This is due to the newer image using the `mssql-tools18` apt package.
* The `sqlcmd` invocation now requires the `-C` option to automatically trust the server certificate.

Update the version of mssql used in tests

---

README.md
sqlrunner/__init__.py
sqlrunner/main.py
tests/test_main.py

The name of the table we are checking against has changed back to `PatientsWithTypeOneDissent`.
We want to check for both the old and the new name in comments, so that we don't have to change existing queries that reference the old name to explain why T1OO data haven't been excluded.

Check for PatientsWithTypeOneDissent in query

---

.github/workflows/build_and_publish.yml

We may never have a v2, but this allows us to not use :latest in *any* action images.

Publish the latest image as v1
